# Generated by Django 6.0.1 on 2026-01-30 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_relpath_quarantine', models.CharField(max_length=500)),
                ('storage_relpath_clean', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('DELETED', 'Deleted')], default='UPLOADED', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to='authn.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authn.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('QUARANTINED', 'Quarantined')], default='QUEUED', max_length=20)),
                ('stage', models.CharField(choices=[('SCANNING', 'Scanning'), ('CONVERTING', 'Converting'), ('EXPORTING', 'Exporting'), ('CHUNKING', 'Chunking'), ('FINALIZING', 'Finalizing')], default='SCANNING', max_length=20)),
                ('options_json', models.JSONField(blank=True, default=dict)),
                ('docling_version', models.CharField(blank=True, max_length=50)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('scan_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('convert_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('export_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('error_details_json', models.JSONField(blank=True, null=True)),
                ('worker_hostname', models.CharField(blank=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_by_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to='authn.apikey')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authn.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('kind', models.CharField(choices=[('docling_json', 'Docling JSON'), ('markdown', 'Markdown'), ('text', 'Text'), ('doctags', 'DocTags'), ('chunks_json', 'Chunks JSON'), ('figures_zip', 'Figures ZIP')], max_length=30)),
                ('storage_relpath', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_by_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts_created', to='authn.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='authn.tenant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='documents.ingestionjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='documents_d_tenant__1461e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('tenant', 'sha256'), name='uniq_document_sha256_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'status'], name='documents_i_tenant__124001_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'stage'], name='documents_i_tenant__2f16a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['document'], name='documents_i_documen_45f565_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'job'], name='documents_a_tenant__4fe460_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('tenant', 'job', 'kind'), name='uniq_artifact_kind_per_job'),
        ),
    ]
