# Generated by Django 6.0.1 on 2026-01-31 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_artifact_expires_at_document_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.ingestionjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
