# Generated by Django 6.0.1 on 2026-02-03 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_tenant_docling_options_json'),
        ('documents', '0003_jobevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='external_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhooks_created', to='authn.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='authn.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('event_type', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRYING', 'Retrying'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='documents.webhookendpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['tenant', 'enabled'], name='documents_w_tenant__c38c60_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'status'], name='documents_w_endpoint_f61d44_idx'),
        ),
    ]
