# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_external_uuid_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="profile",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
