# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_job_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="comparison_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="source_relpath",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(fields=["comparison_id"], name="documents_i_comparison_274fbb_idx"),
        ),
    ]
