# Generated by Django 6.0.1 on 2026-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_job_comparison'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingestionjob',
            new_name='documents_i_compari_451f04_idx',
            old_name='documents_i_comparison_274fbb_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='documents_w_endpoin_b9382a_idx',
            old_name='documents_w_endpoint_f61d44_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='documents_w_tenant__6f243d_idx',
            old_name='documents_w_tenant__c38c60_idx',
        ),
    ]
