# Generated by Django 5.2.14 on 2026-06-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_apikey_is_dashboard_test_key'),
        ('documents', '0008_job_runtime_and_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='created_via',
            field=models.CharField(choices=[('API', 'Public API'), ('DASHBOARD', 'Dashboard')], default='API', max_length=20),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='created_via',
            field=models.CharField(choices=[('API', 'Public API'), ('DASHBOARD', 'Dashboard')], default='API', max_length=20),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='dashboard_last_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='dashboard_last_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_jobs_touched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'created_via'], name='documents_d_tenant__34f676_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'created_via'], name='documents_i_tenant__a4590f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'dashboard_last_action_at'], name='documents_i_tenant__c37323_idx'),
        ),
    ]
