# Generated by Django 6.0.1 on 2026-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='docling_options_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
