# Generated by Django 6.0.1 on 2026-02-08 08:23

import authn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_tenant_docling_options_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_upload_mime_types',
            field=models.JSONField(blank=True, default=authn.models._default_allowed_upload_mime_types),
        ),
    ]
