from django.urls import path

from .web_views import (
    DashboardPageView,
    DashboardToolsPageView,
    DashboardJobDetailPageView,
    DashboardJobsPageView,
    DashboardUploadPageView,
    DoclingProfilesPageView,
    ProfileComparisonPageView,
    RuntimeDiagnosticsPageView,
    api_key_detail,
    api_key_new,
    api_keys_list,
    dashboard_api_artifact_preview,
    dashboard_api_compare,
    dashboard_api_context,
    dashboard_api_document_ingest,
    dashboard_api_documents,
    dashboard_api_jobs,
    dashboard_api_job_retry,
    dashboard_api_options_resolve,
    runtime_smoke,
    runtime_status,
    system_status,
    webhook_deliveries_list,
    webhook_delivery_detail,
    webhook_detail,
    webhook_new,
    webhooks_list,
)


urlpatterns = [
    path("", DashboardPageView.as_view(), name="dashboard-ui"),
    path("tools/", DashboardToolsPageView.as_view(), name="dashboard-tools"),
    path("upload/", DashboardUploadPageView.as_view(), name="dashboard-upload"),
    path("jobs/", DashboardJobsPageView.as_view(), name="dashboard-jobs"),
    path("jobs/<int:pk>/", DashboardJobDetailPageView.as_view(), name="dashboard-job-detail"),
    path("compare/", ProfileComparisonPageView.as_view(), name="dashboard-compare"),
    path("profiles/", DoclingProfilesPageView.as_view(), name="dashboard-profiles"),
    path("system", system_status, name="dashboard-system"),
    path("runtime/", RuntimeDiagnosticsPageView.as_view(), name="dashboard-runtime-ui"),
    path("runtime/status", runtime_status, name="dashboard-runtime-status"),
    path("runtime/smoke", runtime_smoke, name="dashboard-runtime-smoke"),
    path("api/context", dashboard_api_context, name="dashboard-api-context"),
    path("api/documents/", dashboard_api_documents, name="dashboard-api-documents"),
    path("api/jobs/", dashboard_api_jobs, name="dashboard-api-jobs"),
    path(
        "api/documents/<uuid:document_uuid>/ingest/",
        dashboard_api_document_ingest,
        name="dashboard-api-document-ingest",
    ),
    path(
        "api/documents/<int:pk>/compare/",
        dashboard_api_compare,
        name="dashboard-api-document-compare",
    ),
    path("api/jobs/<int:pk>/retry/", dashboard_api_job_retry, name="dashboard-api-job-retry"),
    path(
        "api/artifacts/<int:pk>/preview/",
        dashboard_api_artifact_preview,
        name="dashboard-api-artifact-preview",
    ),
    path(
        "api/docling/options/resolve/",
        dashboard_api_options_resolve,
        name="dashboard-api-options-resolve",
    ),
    path("api-keys/", api_keys_list, name="dashboard-api-keys"),
    path("api-keys/new/", api_key_new, name="dashboard-api-keys-new"),
    path("api-keys/<int:pk>/", api_key_detail, name="dashboard-api-key-detail"),
    path("webhooks/", webhooks_list, name="dashboard-webhooks"),
    path("webhooks/new/", webhook_new, name="dashboard-webhooks-new"),
    path("webhooks/<int:pk>/", webhook_detail, name="dashboard-webhooks-detail"),
    path("webhook-deliveries/", webhook_deliveries_list, name="dashboard-webhook-deliveries"),
    path(
        "webhook-deliveries/<int:pk>/",
        webhook_delivery_detail,
        name="dashboard-webhook-delivery-detail",
    ),
]
