# Generated by Django 5.2.14 on 2026-06-03 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authn', '0004_apikey_is_dashboard_test_key'),
        ('documents', '0008_job_runtime_and_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('action', models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document upload'), ('DOCUMENT_DUPLICATE_REUSE', 'Document duplicate reuse'), ('DOCUMENT_INGEST', 'Document ingest'), ('JOB_RETRY', 'Job retry'), ('DOCUMENT_COMPARE', 'Document compare'), ('ARTIFACT_PREVIEW', 'Artifact preview')], max_length=40)),
                ('potentially_billable', models.BooleanField(default=False)),
                ('tenant_name', models.CharField(blank=True, max_length=200)),
                ('api_key_name', models.CharField(blank=True, max_length=200)),
                ('api_key_prefix', models.CharField(blank=True, max_length=8)),
                ('request_meta_json', models.JSONField(blank=True, default=dict)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to='authn.apikey')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to='documents.artifact')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to='documents.document')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to='documents.ingestionjob')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_action_audits', to='authn.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'action', 'created_at'], name='dashboard_d_tenant__3d3373_idx'), models.Index(fields=['created_by_user', 'created_at'], name='dashboard_d_created_3003df_idx'), models.Index(fields=['potentially_billable', 'created_at'], name='dashboard_d_potenti_b34cd4_idx')],
            },
        ),
    ]
